// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["KUTHE_DATABASE_URL"] || "prisma+postgres://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqd3RfaWQiOjEsInNlY3VyZV9rZXkiOiJza19fY0V1c2YyUU5leVBBa3VaZ3RmU2EiLCJhcGlfa2V5IjoiMDFLTkpUMjBIRUJUNDNZQlRORTc4NUMwOEMiLCJ0ZW5hbnRfaWQiOiJkMjBhNzI3Zjk4Zjk4MWQxOGFmNTg2YmU2ZTYzODc4OWE0Y2M4ZjhjYWFiODlmYTRmYThkYzcyYTYxOTkzZWE5IiwiaW50ZXJuYWxfc2VjcmV0IjoiNjk0NjMyZTYtYTc3NC00OGM3LTk0NTQtOGYxMWIxMDNlZDdmIn0.3yCya46Rv1xJ3a_Y5d390AOPt252o420vfjBpu5I4AM",
  },
});
